"""CLAUDE.md Markdown renderer."""

from __future__ import annotations

from typing import TYPE_CHECKING

from jinja2 import BaseLoader, Environment

if TYPE_CHECKING:
    from codegraph.context.pack_generator import ContextPack

_TEMPLATE = """\
# codeGraph Knowledge Pack — {{ pack.repo_name }}

> Auto-generated by codeGraph on {{ pack.generated_at[:19] }} UTC.
> Token budget: {{ pack.token_budget }}. Full graph available via MCP (`codegraph serve`).

## Repository Overview

| Metric | Value |
|--------|-------|
| Files | {{ pack.repo_overview.get('files', 0) }} |
| Functions | {{ pack.repo_overview.get('functions', 0) }} |
| Classes | {{ pack.repo_overview.get('classes', 0) }} |
| Test files | {{ pack.repo_overview.get('test_files', 0) }} |
| Graph edges | {{ pack.repo_overview.get('edge_count', 0) }} |
| Languages | {{ pack.repo_overview.get('languages', {}) | dictsort | map('join', ': ') | join(', ') }} |

## Architectural Layers

{% for layer, files in pack.architectural_layers.items() | sort %}
**{{ layer | title }}** ({{ files | length }} files)
{% for f in files[:5] %}- `{{ f }}`
{% endfor %}{% if files | length > 5 %}- ... and {{ files | length - 5 }} more
{% endif %}
{% endfor %}

## Hot Paths (Most Active Code)

| # | Name | Kind | File | Commits | Complexity |
|---|------|------|------|---------|------------|
{% for h in pack.hot_paths[:10] %}| {{ loop.index }} | `{{ h.name }}` | {{ h.kind }} | `{{ h.get('file','').replace('file:','') | truncate(45, True, '…') }}` | {{ h.commit_count }} | {{ h.complexity }} |
{% endfor %}

## Recent Changes

{% for c in pack.recent_changes %}
### `{{ c.get('short_sha', c.get('sha','')[:7]) }}` — {{ c.get('author','') }}
{{ c.get('message', '') | truncate(120) }}
{% if c.get('impacted_symbols') %}_Impacted_: {{ c.impacted_symbols | map(attribute='name') | select | list | join(', ') | truncate(180) }}
{% endif %}
{% endfor %}

## Public API Surface

{% for api in pack.public_api_summary %}
- `{{ api.name }}` *({{ api.kind }})* — `{{ api.file }}` — {{ api.sig | truncate(70) }}
{% endfor %}

## Key Classes

{% for c in pack.key_classes %}
- **`{{ c.name }}`** (`{{ c.file }}`){% if c.bases %} extends {{ c.bases | join(', ') }}{% endif %}{% if c.docstring %} — {{ c.docstring | truncate(80) }}{% endif %}

{% endfor %}

## Open TODOs ({{ pack.todos | length }})

{% for t in pack.todos %}
- **{{ t.kind }}** `{{ t.file }}:{{ t.line }}` — {{ t.text | truncate(100) }}
{% endfor %}

{% if pack.session_notes %}
## Session Notes ({{ pack.session_notes | length }} most recent)

{% for n in pack.session_notes %}
**{{ n.timestamp }}** · *{{ n.category }}*

{{ n.note | truncate(300) }}

{% endfor %}
{% endif %}

---

*Query the full graph: `codegraph query <symbol>` or via MCP tool `codegraph_find_symbol`.*
*Graph size: {{ pack.symbol_count }} nodes across {{ pack.file_count }} files.*
"""


def _datetimeformat(ts: int) -> str:
    from datetime import datetime, timezone

    try:
        return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%d")
    except Exception:
        return str(ts)


class ClaudeMdWriter:
    def __init__(self, pack: "ContextPack"):
        self.pack = pack

    def render(self) -> str:
        env = Environment(loader=BaseLoader(), autoescape=False)
        env.filters["datetimeformat"] = _datetimeformat
        env.filters["truncate"] = self._truncate_filter
        tmpl = env.from_string(_TEMPLATE)
        return tmpl.render(pack=self.pack)

    @staticmethod
    def _truncate_filter(s: str, length: int = 80, end: bool = True, ellipsis: str = "...") -> str:
        if not isinstance(s, str):
            s = str(s)
        if len(s) <= length:
            return s
        return s[: length - len(ellipsis)] + ellipsis
